TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DATA += devWeeder.proto

DB += devWeeder.db

#=======================================
include $(TOP)/configure/RULES
